"""
Django settings for emis project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.utils.translation import gettext_lazy as _
from datetime import timedelta


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+mb146sw)3ayx06d&0#hbeh1-^43=(py6akp9+)t55^l0nug88'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django_auto_logout',
    'eims',
    'widget_tweaks',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'django_auto_logout.middleware.auto_logout',  # Removed - using custom session monitoring
]

ROOT_URLCONF = 'emis.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'eims' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'eims.context_processors.env_flags',
            ],
        },
    },
]


WSGI_APPLICATION = 'emis.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Default to SQLite for development. If POSTGRES_* environment variables are provided,
# switch to PostgreSQL automatically.
POSTGRES_HOST = os.getenv('POSTGRES_HOST')
POSTGRES_PORT = os.getenv('POSTGRES_PORT', '5432')
POSTGRES_DB = os.getenv('POSTGRES_DB')
POSTGRES_USER = os.getenv('POSTGRES_USER')
POSTGRES_PASSWORD = os.getenv('POSTGRES_PASSWORD')

if POSTGRES_HOST and POSTGRES_DB and POSTGRES_USER:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'HOST': POSTGRES_HOST,
            'PORT': POSTGRES_PORT,
            'NAME': POSTGRES_DB,
            'USER': POSTGRES_USER,
            'PASSWORD': POSTGRES_PASSWORD or '',
            # Keep DB connections open for up to 5 minutes to reduce churn under load
            'CONN_MAX_AGE': int(os.getenv('CONN_MAX_AGE', '300')),
            'OPTIONS': {
                # 'sslmode': os.getenv('POSTGRES_SSLMODE', 'prefer'),
            }
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

AUTO_LOGOUT = {
        'IDLE_TIME': timedelta(minutes=30),  # Logout after 10 minutes of inactivity
        # 'SESSION_TIME': timedelta(minutes=), # Logout after 1 hour from last login (optional)
        'MESSAGE': 'Your session has expired due to inactivity. Please log in again.', # Optional message
    }

# Environment flags (default values; can be overridden per environment)
IS_STAGING = False
SITE_NAME = os.getenv('SITE_NAME', 'EMIS Dashboard')