# Generated by Django 5.2.2 on 2025-06-09 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentCenterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(choices=[('Central', 'Central'), ('Western', 'Western'), ('Eastern', 'Eastern'), ('Northern', 'Northern')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OccupationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_number', models.CharField(max_length=50, unique=True)),
                ('center_name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eims.assessmentcentercategory')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eims.district')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5)),
                ('min_score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('type', models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical')], max_length=10)),
            ],
            options={
                'ordering': ['-type', '-min_score'],
                'unique_together': {('grade', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('structure_type', models.CharField(choices=[('modules', 'Modules'), ('papers', 'Papers')], help_text='Specify whether this occupation uses modules or papers', max_length=10)),
                ('levels', models.ManyToManyField(related_name='occupations', to='eims.level')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eims.occupationcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eims.level')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eims.occupation')),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='occupation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eims.occupation'),
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('grade_type', models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical')], max_length=10)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eims.level')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eims.occupation')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eims.district')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('passport_photo', models.ImageField(upload_to='photos/')),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('entry_year', models.IntegerField()),
                ('intake', models.CharField(choices=[('March', 'March'), ('August', 'August')], max_length=10)),
                ('registration_category', models.CharField(choices=[('formal', 'Formal'), ('modular', 'Modular'), ('informal', "Informal / Worker's PAS")], max_length=10)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('assessment_date', models.DateField()),
                ('reg_number', models.CharField(blank=True, max_length=255, unique=True)),
                ('assessment_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eims.assessmentcenter')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eims.district')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eims.level')),
                ('modules', models.ManyToManyField(blank=True, to='eims.module')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eims.occupation')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eims.village')),
            ],
        ),
        migrations.AddField(
            model_name='assessmentcenter',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eims.village'),
        ),
    ]
