# Generated by Django 5.2.2 on 2025-06-09 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eims', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='occupation',
        ),
    ]
