# Generated by Django 5.2.2 on 2025-06-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eims', '0002_remove_level_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
