# Generated by Django 5.2.2 on 2025-06-09 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eims', '0003_alter_candidate_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='level',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='modules',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='assessment_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eims.assessmentcenter'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eims.district'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='entry_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='intake',
            field=models.CharField(choices=[('M', 'March'), ('A', 'August')], max_length=6),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='nationality',
            field=models.CharField(choices=[('U', 'Ugandan'), ('X', 'Foreigner')], max_length=1),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eims.occupation'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_photos/'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='reg_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='registration_category',
            field=models.CharField(choices=[('Formal', 'Formal'), ('Modular', 'Modular'), ('Informal', "Worker's PAS")], max_length=10),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eims.village'),
        ),
    ]
