# Generated by Django 5.2.2 on 2025-06-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eims', '0004_rename_dob_candidate_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='enrollment_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_enrolled',
            field=models.BooleanField(default=False),
        ),
    ]
