# Generated by Django 5.2.2 on 2025-06-10 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eims', '0005_candidate_enrollment_label_candidate_is_enrolled'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eims.candidate')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eims.level')),
            ],
        ),
    ]
