# Generated by Django 5.2.2 on 2025-06-10 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eims', '0006_candidatelevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eims.candidate')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eims.module')),
            ],
        ),
    ]
