# Generated by Django 5.2.2 on 2025-06-10 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eims', '0007_candidatemodule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='is_enrolled',
        ),
    ]
